//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Windows Form Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Andloe.Presentacion
{
    partial class FormReporteFacturaRI
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer? components = null;

        private System.Windows.Forms.Panel pnlTop;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Button btnCerrar;
        private System.Windows.Forms.Button btnImprimir;
        private System.Windows.Forms.Button btnExportPdf;
        private System.Windows.Forms.Button btnExportExcel;

        private Microsoft.Reporting.WinForms.ReportViewer reportViewer1;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                try
                {
                    if (components != null)
                        components.Dispose();

                    // El ReportViewer a veces mantiene recursos nativos
                    reportViewer1?.Dispose();
                }
                catch { }
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            pnlTop = new Panel();
            btnExportExcel = new Button();
            btnExportPdf = new Button();
            btnImprimir = new Button();
            btnCerrar = new Button();
            lblTitulo = new Label();
            reportViewer1 = new Microsoft.Reporting.WinForms.ReportViewer();
            pnlTop.SuspendLayout();
            SuspendLayout();
            // 
            // pnlTop
            // 
            pnlTop.BackColor = Color.FromArgb(46, 51, 73);
            pnlTop.Controls.Add(btnExportExcel);
            pnlTop.Controls.Add(btnExportPdf);
            pnlTop.Controls.Add(btnImprimir);
            pnlTop.Controls.Add(btnCerrar);
            pnlTop.Controls.Add(lblTitulo);
            pnlTop.Dock = DockStyle.Top;
            pnlTop.Location = new Point(0, 0);
            pnlTop.Name = "pnlTop";
            pnlTop.Padding = new Padding(12, 10, 12, 10);
            pnlTop.Size = new Size(1100, 56);
            pnlTop.TabIndex = 0;
            // 
            // btnExportExcel
            // 
            btnExportExcel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnExportExcel.BackColor = Color.FromArgb(24, 30, 54);
            btnExportExcel.FlatAppearance.BorderSize = 0;
            btnExportExcel.FlatStyle = FlatStyle.Flat;
            btnExportExcel.ForeColor = Color.White;
            btnExportExcel.Location = new Point(836, 12);
            btnExportExcel.Name = "btnExportExcel";
            btnExportExcel.Size = new Size(96, 32);
            btnExportExcel.TabIndex = 4;
            btnExportExcel.Text = "Excel";
            btnExportExcel.UseVisualStyleBackColor = false;
            // 
            // btnExportPdf
            // 
            btnExportPdf.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnExportPdf.BackColor = Color.FromArgb(24, 30, 54);
            btnExportPdf.FlatAppearance.BorderSize = 0;
            btnExportPdf.FlatStyle = FlatStyle.Flat;
            btnExportPdf.ForeColor = Color.White;
            btnExportPdf.Location = new Point(734, 12);
            btnExportPdf.Name = "btnExportPdf";
            btnExportPdf.Size = new Size(96, 32);
            btnExportPdf.TabIndex = 3;
            btnExportPdf.Text = "PDF";
            btnExportPdf.UseVisualStyleBackColor = false;
            // 
            // btnImprimir
            // 
            btnImprimir.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnImprimir.BackColor = Color.FromArgb(24, 30, 54);
            btnImprimir.FlatAppearance.BorderSize = 0;
            btnImprimir.FlatStyle = FlatStyle.Flat;
            btnImprimir.ForeColor = Color.White;
            btnImprimir.Location = new Point(632, 12);
            btnImprimir.Name = "btnImprimir";
            btnImprimir.Size = new Size(96, 32);
            btnImprimir.TabIndex = 2;
            btnImprimir.Text = "Imprimir";
            btnImprimir.UseVisualStyleBackColor = false;
            // 
            // btnCerrar
            // 
            btnCerrar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnCerrar.BackColor = Color.FromArgb(231, 76, 60);
            btnCerrar.FlatAppearance.BorderSize = 0;
            btnCerrar.FlatStyle = FlatStyle.Flat;
            btnCerrar.ForeColor = Color.White;
            btnCerrar.Location = new Point(938, 12);
            btnCerrar.Name = "btnCerrar";
            btnCerrar.Size = new Size(150, 32);
            btnCerrar.TabIndex = 1;
            btnCerrar.Text = "Cerrar";
            btnCerrar.UseVisualStyleBackColor = false;
            // 
            // lblTitulo
            // 
            lblTitulo.AutoSize = true;
            lblTitulo.Dock = DockStyle.Left;
            lblTitulo.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            lblTitulo.ForeColor = Color.White;
            lblTitulo.Location = new Point(12, 10);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Padding = new Padding(0, 6, 0, 0);
            lblTitulo.Size = new Size(224, 27);
            lblTitulo.TabIndex = 0;
            lblTitulo.Text = "Representación Impresa (RI)";
            // 
            // reportViewer1
            // 
            reportViewer1.Dock = DockStyle.Fill;
            reportViewer1.Location = new Point(0, 56);
            reportViewer1.Name = "reportViewer1";
            reportViewer1.ServerReport.BearerToken = null;
            reportViewer1.Size = new Size(1100, 644);
            reportViewer1.TabIndex = 1;
            // 
            // FormReporteFacturaRI
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(1100, 700);
            Controls.Add(reportViewer1);
            Controls.Add(pnlTop);
            MinimumSize = new Size(980, 600);
            Name = "FormReporteFacturaRI";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Representación Impresa - Factura";
            WindowState = FormWindowState.Maximized;
            pnlTop.ResumeLayout(false);
            pnlTop.PerformLayout();
            ResumeLayout(false);

        }

        #endregion
    }
}
#nullable restore
